### ISSUE TITLE
installing ccppetmr fails in SL7

### ISSUE THREAD

**Issue by TomasKulhanek** [vais-ral/CCPi-VirtualMachine#7]
Launching `./UPDATE.sh` from https://github.com/CCPPETMR/CCPPETMR_VM.git fails in SL7 on following:
- [x] cmake: no such file or directory; cmake3 is present in SL7, solved by making symbolic link /usr/bin/cmake to /usr/bin/cmake3
- [ ] `#include "fftw3.h"` no such file in `/home/vagrant/devel/buildVM/sources/ISMRMRD/utilities/..`; `fftw3.h` is present in `/usr/include`, unfortunately manual changing to `#include <fftw3.h>` seems not to search `/usr/include`; workaround to edit the failing files `#include "/usr/lib/fftw3.h"`
- [ ] `/opt/ccpi/envs/py3/include/ITK-4.11/vcl_compiler.h:79:4: error: #error "Dunno about this gcc" #  error "Dunno about this gcc"` - seems that new GCC is not expected?? `gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)`

**Comment by paskino** [comment]
FFTW3 should be found with [FindFFTW3.cmake](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/CMake/FindFFTW3.cmake). It seems that passing [`FFTW3_ROOT_DIR`](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/CMake/FindFFTW3.cmake#L107) variable to cmake could help. 

What is strange is that in Ubuntu you find the file in the exact same location [`/usr/include/fftw3.h`](https://packages.ubuntu.com/xenial/amd64/libfftw3-dev/filelist)

**Comment by TomasKulhanek** [comment]
Attached [vagrant.log](https://github.com/vais-ral/CCPi-VirtualMachine/files/2615860/vagrant.log) with `fftw3.h` and `Dunno about this gcc` errors.

**Comment by paskino** [comment]
It seems to have found the proper FFTW3 library. 
```
2483: default: FFTW3 UNIX libraries: /usr/lib64/libfftw3.so
2484: default: -- Found FFTW3: /usr/lib64/libfftw3.so  
2485: default: -- USING the system FFTW3, found FFTW3_INCLUDE_DIR=/usr/include,
```
and at 
```
16774 default: -- FFTW3 UNIX libraries: /usr/lib64/libfftw3f.so
16775   default: -- Found FFTW3: /usr/lib64/libfftw3f.so  
16776  default: FFTW3 and Boost Found... building utilities
```

however, it doesn't work.

Could you please run `UPDATE.sh` with one thread? Now the output of the log is interleaving 2 progresses (both of which fail) and it's not easy to understand what went wrong. 

This can be achieved by calling  `UPDATE.sh -j 1` at [this line](https://github.com/vais-ral/CCPi-VirtualMachine/blob/master/scripts/bootstrappetmr.sh#L124).

**Comment by TomasKulhanek** [comment]
moved UPDATE.sh into this git repo, added 	  -DUSE_SYSTEM_ACE=Off \ 
```
    default: -- Configuring incomplete, errors occurred!
    default: See also "/root/devel/buildVM/builds/Gadgetron/build/CMakeFiles/CMakeOutput.log".
    default: CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    default: Please set them or make sure they are set and tested correctly in the CMake files:
    default: ACE_INCLUDE_DIR
```
attached vagrant.log
[vagrant.log](https://github.com/vais-ral/CCPi-VirtualMachine/files/2632175/vagrant.log)

**Comment by paskino** [comment]
The log says:
```
default: usage: conda [-h] [-V] command ...
    default: conda: error: unrecognized arguments: conda-forge paskino
    default: Solving environment: ...working... 
    default: failed
    default: 
    default: PackagesNotFoundError: The following packages are not available from current channels:
    default: 
    default:   - ccpi-segmentation
    default:   - ccpi-quantification
    default:   - ccpi-regulariser
    default:   - ccpi-preprocessing
    default:   - ace
    default:   - ccpi-reconstruction
    default: 
    default: Current channels:
    default: 
    default:   - https://repo.anaconda.com/pkgs/main/linux-64
    default:   - https://repo.anaconda.com/pkgs/main/noarch
    default:   - https://repo.anaconda.com/pkgs/free/linux-64
    default:   - https://repo.anaconda.com/pkgs/free/noarch
    default:   - https://repo.anaconda.com/pkgs/r/linux-64
    default:   - https://repo.anaconda.com/pkgs/r/noarch
    default:   - https://repo.anaconda.com/pkgs/pro/linux-64
    default:   - https://repo.anaconda.com/pkgs/pro/noarch
    default: 
```

Apparently the [command that was issued](https://github.com/vais-ral/CCPi-VirtualMachine/blob/master/scripts/bootstrapconda.sh#L22) is not correct? Maybe it does not accept a list of channels. Try one command each.

`ACE` must be installed from my conda channel `paskino` before build. Or alternatively set the [`USE_SYSTEM_ACE`](https://github.com/vais-ral/CCPi-VirtualMachine/blob/master/scripts/UPDATE.sh#L144) to `OFF`.
